"""
OpenClaw 平台适配器

将统一格式配置转换为 OpenClaw 所需的文件格式。
"""

from pathlib import Path
from typing import Dict, Any, Optional


def adapt(
    agent_name: str,
    agent_config: Dict[str, Any],
    soul_content: Optional[str],
    user_config: Dict[str, Any],
    output_dir: Path,
    hub_root: Path
) -> None:
    """
    适配函数：将统一配置转换为 OpenClaw 格式
    """
    # 生成 agent.md（对应 OpenClaw 的 AGENTS.md）
    _generate_agent_md(agent_name, agent_config, output_dir, hub_root)

    # 生成 soul.md
    _generate_soul_md(agent_name, soul_content, output_dir, hub_root)

    # 生成 user.md
    _generate_user_md(agent_name, user_config, output_dir, hub_root)

    # 生成 identity.md（如果配置中有额外身份字段）
    _generate_identity_md(agent_name, agent_config, output_dir, hub_root)


def _generate_agent_md(agent_name: str, config: Dict, output_dir: Path, hub_root: Path) -> None:
    """生成 OpenClaw 格式的 agent.md"""
    content = f"""<!-- AUTO-GENERATED by openclaw-hub adapter -->
<!-- Source: standards/agents/{agent_name}/agent.yaml -->
<!-- DO NOT EDIT DIRECTLY; edit the source file instead -->

# {config.get('name', agent_name)} - Agent 配置

## 基本信息

- **Name:** {config.get('name', agent_name)}
- **Creature:** {config.get('creature', 'Unknown')}
- **Emoji:** {config.get('emoji', '🤖')}

## 能力

"""
    capabilities = config.get('capabilities', [])
    if capabilities:
        for cap in capabilities:
            content += f"- {cap}\n"
    else:
        content += "- 待配置\n"

    content += "\n## 工具\n\n"
    tools = config.get('tools', [])
    if tools:
        for tool in tools:
            content += f"- {tool}\n"
    else:
        content += "- 待配置\n"

    # 添加平台特定配置
    platform_config = config.get('platform_config', {}).get('openclaw', {})
    if platform_config:
        content += f"\n## OpenClaw 配置\n\n"
        for key, value in platform_config.items():
            content += f"- **{key}:** {value}\n"

    # 添加通用规范引用
    content += f"""
## 规范

参见通用规范:
- [工作流](../../../../../standards/common/WORKFLOW.md)
- [语言规范](../../../../../standards/common/LANGUAGE.md)
- [文档习惯](../../../../../standards/common/DOCUMENTATION.md)
"""

    output_path = output_dir / "agent.md"
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)


def _generate_soul_md(agent_name: str, soul_content: Optional[str], output_dir: Path, hub_root: Path) -> None:
    """生成 soul.md"""
    if soul_content is None:
        soul_content = "# Soul\n\n待配置...\n"

    header = f"""<!-- AUTO-GENERATED by openclaw-hub adapter -->
<!-- Source: standards/agents/{agent_name}/soul.md -->
<!-- DO NOT EDIT DIRECTLY; edit the source file instead -->

"""

    output_path = output_dir / "soul.md"
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header + soul_content)


def _generate_user_md(agent_name: str, user_config: Dict, output_dir: Path, hub_root: Path) -> None:
    """生成 user.md"""
    content = f"""<!-- AUTO-GENERATED by openclaw-hub adapter -->
<!-- Source: standards/agents/{agent_name}/user.yaml -->
<!-- DO NOT EDIT DIRECTLY; edit the source file instead -->

# User 配置

- **Name:** {user_config.get('name', 'Unknown')}
- **称呼方式:** {', '.join(user_config.get('address_as', [])) if isinstance(user_config.get('address_as'), list) else user_config.get('address_as', 'Unknown')}
- **时区:** {user_config.get('timezone', 'Unknown')}

## 背景

{user_config.get('context', '待配置...')}

## 偏好

- **语言:** {user_config.get('preferences', {}).get('language', 'zh')}
- **沟通风格:** {user_config.get('preferences', {}).get('communication_style', '待配置')}
- **详细程度:** {user_config.get('preferences', {}).get('detail_level', 'moderate')}
"""

    output_path = output_dir / "user.md"
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)


def _generate_identity_md(agent_name: str, config: Dict, output_dir: Path, hub_root: Path) -> None:
    """生成 identity.md（OpenClaw 特有）"""
    content = f"""<!-- AUTO-GENERATED by openclaw-hub adapter -->
<!-- Source: standards/agents/{agent_name}/agent.yaml -->
<!-- DO NOT EDIT DIRECTLY; edit the source file instead -->

# Identity

- **Name:** {config.get('name', agent_name)}
- **Creature:** {config.get('creature', 'Unknown')}
- **Emoji:** {config.get('emoji', '🤖')}
- **Avatar:** {config.get('avatar', '')}

---

_配置文件由 openclaw-hub 自动生成，如需修改请编辑 standards/agents/{agent_name}/ 下的源文件。_
"""

    output_path = output_dir / "identity.md"
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
